'use strict';
/* 활성 규칙 (active-rule generated task) edit-scope picker.
   Mirrors the existing repeat-rule scope picker (this/future/all) but for
   tasks generated by applyActiveTaskRules() (_ruleGen / _ruleId).

   Slices:
   - loadTaskRules / saveTaskRules (rule storage helpers)
   - propagateRepeatEdit / propagateActiveRuleEdit
   - _writeTaskFromModal / _syncSpecialToggle / _applyRepeatScopeEdit

   Tests:
   1. scope 'this' → only the edited task changes; rule + siblings untouched,
      and the task is detached (_occurrenceCustomized).
   2. scope 'future' → rule template (taskText/taskCatId/taskPriority) is
      updated but existing siblings are left alone.
   3. scope 'all' → rule template updated AND every existing sibling
      (including a `done:true` one) gets the new text/catId/priority. */
const { readIndex, sliceBlock, runner } = require('./lib');
const vm = require('vm');

const html = readIndex();
const rulesBlock = sliceBlock(html, 'function loadTaskRules(){', '\nvar taskRules');
const propagateBlock = sliceBlock(html, 'function propagateRepeatEdit(ruleId, fromDate, mode, fields, excludeId){', '\n/* Update the timetable slot definition');
const applyBlock = sliceBlock(html, 'function _writeTaskFromModal(task,fields){', '\nfunction taskLinkTargetLabel(');

function makeSandbox(initial) {
  const store = { task_rules_v1: JSON.stringify(initial.rules || []) };
  const sb = {
    window: {},
    console: { error() {}, warn() {}, log() {}, debug() {} },
    localStorage: {
      getItem: (k) => (k in store ? store[k] : null),
      setItem: (k, v) => { store[k] = String(v); },
      removeItem: (k) => { delete store[k]; },
    },
    setReturnStorageItem: (k, v) => { store[k] = String(v); return true; },
    repairGeneratedTasks: () => {},
    tasks: initial.tasks || [],
    taskRules: initial.rules || [],
    Date,
    // saveModal-adjacent globals touched by _applyRepeatScopeEdit
    saveTaskData: () => {},
    renderProjects: undefined,
    renderList: () => {},
    renderCal: () => {},
    tasksCloseModal: () => {},
    taskModalSnapshot: null,
    taskModalDraft: null,
    markTaskDateManualChange: () => {},
    // unused in 'rule' kind, but referenced by sibling scopes in the slice
    syncTaskRepeatItem: () => {},
    applyTtSlotEdit: () => {},
  };
  vm.createContext(sb);
  vm.runInContext(rulesBlock, sb);
  vm.runInContext(propagateBlock, sb);
  vm.runInContext(applyBlock, sb);
  return { sb, store };
}

const t = runner('Active-rule (활성 규칙) edit-scope picker');

function makeTasks() {
  return [
    { id: 1, text: '단어 외우기', catId: 'study', priority: 'mid', date: '2026-06-11', deadlineDate: '2026-06-11', _ruleId: 'r1', _ruleGen: true, done: false },
    { id: 2, text: '단어 외우기', catId: 'study', priority: 'mid', date: '2026-06-12', deadlineDate: '2026-06-12', _ruleId: 'r1', _ruleGen: true, done: false },
    { id: 3, text: '단어 외우기', catId: 'study', priority: 'mid', date: '2026-06-10', deadlineDate: '2026-06-10', _ruleId: 'r1', _ruleGen: true, done: true },
    { id: 4, text: '다른 항목', catId: 'etc', priority: 'low', date: '2026-06-12', _ruleId: 'r2', _ruleGen: true, done: false },
  ];
}
function makeRules() {
  return [
    { id: 'r1', taskText: '단어 외우기', taskCatId: 'study', taskPriority: 'mid' },
    { id: 'r2', taskText: '다른 항목', taskCatId: 'etc', taskPriority: 'low' },
  ];
}
const fields = (overrides) => Object.assign({
  text: '단어 30개 외우기', note: '', priority: 'high', date: '2026-06-11',
  deadlineDate: '', deadlineTime: '', isSpecial: false, catId: 'uni',
  projectId: null, timeStart: '', timeEnd: '', travelMin: 0,
}, overrides);

// ── 1. scope 'this' — only this task changes, detached from rule ───────────
{
  const { sb, store } = makeSandbox({ tasks: makeTasks(), rules: makeRules() });
  const task = sb.tasks.find((x) => x.id === 1);
  sb._applyRepeatScopeEdit(task, fields(), 'this', 'rule');

  t.ok('this: edited task gets new text', task.text === '단어 30개 외우기', task.text);
  t.ok('this: edited task gets new catId', task.catId === 'uni', task.catId);
  t.ok('this: edited task detached (_occurrenceCustomized)', task._occurrenceCustomized === true);
  const sibling = sb.tasks.find((x) => x.id === 2);
  t.ok('this: sibling occurrence untouched', sibling.text === '단어 외우기' && sibling.catId === 'study');
  const rules = JSON.parse(store.task_rules_v1);
  const r1 = rules.find((r) => r.id === 'r1');
  t.ok('this: rule template untouched', r1.taskText === '단어 외우기' && r1.taskCatId === 'study');
}

// ── 2. scope 'future' — rule template updated, siblings untouched ──────────
{
  const { sb, store } = makeSandbox({ tasks: makeTasks(), rules: makeRules() });
  const task = sb.tasks.find((x) => x.id === 1);
  sb._applyRepeatScopeEdit(task, fields(), 'future', 'rule');

  t.ok('future: edited task gets new text', task.text === '단어 30개 외우기');
  const rules = JSON.parse(store.task_rules_v1);
  const r1 = rules.find((r) => r.id === 'r1');
  t.ok('future: rule template text updated', r1.taskText === '단어 30개 외우기', r1);
  t.ok('future: rule template catId updated', r1.taskCatId === 'uni', r1);
  t.ok('future: rule template priority updated', r1.taskPriority === 'high', r1);
  const sibling = sb.tasks.find((x) => x.id === 2);
  t.ok('future: existing sibling left as-is', sibling.text === '단어 외우기' && sibling.catId === 'study');
  const r2 = rules.find((r) => r.id === 'r2');
  t.ok('future: other rule untouched', r2.taskText === '다른 항목');
}

// ── 3. scope 'all' — rule template + every sibling (incl. done) updated ────
{
  const { sb, store } = makeSandbox({ tasks: makeTasks(), rules: makeRules() });
  const task = sb.tasks.find((x) => x.id === 1);
  sb._applyRepeatScopeEdit(task, fields(), 'all', 'rule');

  const rules = JSON.parse(store.task_rules_v1);
  const r1 = rules.find((r) => r.id === 'r1');
  t.ok('all: rule template updated', r1.taskText === '단어 30개 외우기' && r1.taskCatId === 'uni' && r1.taskPriority === 'high');

  const sib = sb.tasks.find((x) => x.id === 2);
  t.ok('all: future sibling text updated', sib.text === '단어 30개 외우기', sib.text);
  t.ok('all: future sibling catId updated', sib.catId === 'uni', sib.catId);
  t.ok('all: future sibling priority updated', sib.priority === 'high', sib.priority);

  const past = sb.tasks.find((x) => x.id === 3);
  t.ok('all: done sibling is also updated (no done/undone filter)', past.text === '단어 30개 외우기' && past.catId === 'uni');

  const other = sb.tasks.find((x) => x.id === 4);
  t.ok('all: sibling of a different rule untouched', other.text === '다른 항목' && other.catId === 'etc');
}

// ── 4. scope 'all' — _occurrenceCustomized siblings are skipped ────────────
{
  const tasks = makeTasks();
  tasks[1]._occurrenceCustomized = true; // task id 2
  const { sb } = makeSandbox({ tasks, rules: makeRules() });
  const task = sb.tasks.find((x) => x.id === 1);
  sb._applyRepeatScopeEdit(task, fields(), 'all', 'rule');

  const customized = sb.tasks.find((x) => x.id === 2);
  t.ok('all: customized sibling skipped', customized.text === '단어 외우기' && customized.catId === 'study');
}

t.done();
